### ISSUE TITLE
MySQL database charset might be wrong

### ISSUE THREAD

**Issue by jorgesat** [YunoHost-Apps/linkstack_ynh#25]
There is an issue with encoding non-ASCII characters in the bio text box. It seems to be related to a wrong charset of the MySQL database.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

Install linkstack and add a character like `é` in the profile bio. The character should be non-ASCII. More details can be found in the following issue: https://github.com/LinkStackOrg/LinkStack/issues/519

### Expected behavior

non-ASCII characters are properly encoded.

According to the developers the database should be created with charset `utf8mb4` and collation `utf8mb4_unicode_ci`.

**Comment by JulianPrieber** [comment]
See: https://github.com/LinkStackOrg/LinkStack/blob/main/config/database.php#L56

**Comment by jorgesat** [comment]
> See: https://github.com/LinkStackOrg/LinkStack/blob/main/config/database.php#L56

I have checked and our `collation` value is the same as the one provided in your linked file: `utf8mb4_unicode_ci`

**Comment by JulianPrieber** [comment]
Does this YunoHost app even use MySQL?

**Comment by Tagadda** [comment]
At the moment it's using SQLite.

**Comment by JulianPrieber** [comment]
Then this issue can be closed. @jorgesat what database were you referring to?
SQLite works out of the box.

**Comment by Tagadda** [comment]
Mmh I can reproduce this issue on a fresh install tho'
I'll try to dig into this later

**Comment by JulianPrieber** [comment]
Reproduce what exactly?

**Comment by Tagadda** [comment]
- Install LinkStack on YunoHost
- Add `ééé` to Page Description
- Click `Save`
- Page Description textarea shows `Ã©Ã©Ã©` (`/studio/page`)

**Comment by JulianPrieber** [comment]
Works on docker using sqlite:
![chrome_aonXRavvUM](https://github.com/YunoHost-Apps/linkstack_ynh/assets/60265788/b10541cc-153c-44ca-9fa9-afc330dc8150)
![chrome_4bHA7eKxPR](https://github.com/YunoHost-Apps/linkstack_ynh/assets/60265788/63fa24cf-061f-4054-9ffb-561fd919e7fa)

**Comment by JulianPrieber** [comment]
YunoHost app different story:
![firefox_D0wQvLmNz8](https://github.com/YunoHost-Apps/linkstack_ynh/assets/60265788/d233a721-0b6e-4c2d-87f0-03eeb5925111)

**Comment by Tagadda** [comment]
The database contains `<p>&Atilde;&copy;&Atilde;&copy;&Atilde;&copy;</p>`

**Comment by jorgesat** [comment]
Working fine after last update.

**Comment by jorgesat** [comment]
working fine after updating to version 4.2.6~ynh2
