### ISSUE TITLE
Options contain no next when trying to add a new link

### ISSUE THREAD

**Issue by takouhai** [YunoHost-Apps/linkstack_ynh#54]
### Describe the bug

All `select`ions to add a new link have blank `option`s.

### Context

- Hardware: A 4GB RAM KVM VPS on Racknerd
- YunoHost version: `11.2.9.1`
- I have access to my server: through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using package version/branch: `4.7.2~ynh1`

### Steps to reproduce

- Unsure! This happened after upgrading one day. :( 

### Expected behavior

- User should be able to see the text for the link option they are selecting

### Screenshots

![Screenshot_20240202_215726](https://github.com/YunoHost-Apps/linkstack_ynh/assets/814940/046875a6-9a57-489a-be38-52d3060f7561)

**Comment by takouhai** [comment]
Turns out somewhere my installation of Linkstack didn't properly update the buttons table.

![Screenshot_20240214_191855](https://github.com/YunoHost-Apps/linkstack_ynh/assets/814940/48a505b0-1797-46a0-9e67-329c1587b318)

I manually dropped + recreated the table locally and my instance seems to be working okay now. Not sure how we got here, but I'm glad I figured it out!

**Comment by zeroesca** [comment]
I finally got around to dealing with this issue today. I noticed some missing fields in the links (type, type_params) and users (auth_as) tables, as well.
